# Generated by Django 4.1.7 on 2023-03-20 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_notestags_notes_id_alter_notestags_tags_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notestags',
            name='notes_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.notes'),
        ),
        migrations.AlterField(
            model_name='notestags',
            name='tags_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.tags'),
        ),
    ]
