# Generated by Django 4.1.7 on 2023-03-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_notestags_notes_id_alter_notestags_tags_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
