# Generated by Django 4.1.7 on 2023-03-27 20:02

from django.db import migrations, models
import notes.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_customuser_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='image',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=notes.models.CustomUser.user_dir_path),
        ),
    ]
