# Generated by Django 4.1.7 on 2023-04-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_remove_notes_image_alter_customuser_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
