# Generated by Django 4.1.7 on 2023-04-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='No name', max_length=40, null=True),
        ),
    ]
