# Generated by Django 4.1.7 on 2023-04-04 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.notes')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notes',
            name='likes',
            field=models.ManyToManyField(related_name='note_likes', through='notes.UserLikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
