# Generated by Django 4.1.7 on 2023-04-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_userlikes_notes_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlikes',
            name='value',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Unlike', max_length=8),
        ),
    ]
