# Generated by Django 4.1.7 on 2023-04-08 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_userlikes_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
