# Generated by Django 4.1.7 on 2023-04-12 21:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='', max_length=10000),
        ),
    ]
