# Generated by Django 4.1.7 on 2023-04-13 21:01

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_alter_notes_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
